insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (1, 8, 'Aquamarine', 'Laser', 'Electric', 50, 92, 945);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (2, 1, 'Maroon', 'Kizashi', 'Diesel', 31, 73, 7987);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (3, 17, 'Goldenrod', 'SRX', 'Gas', 28, 83, 7059);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (4, 17, 'Puce', 'Tahoe', 'Electric', 66, 42, 1141);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (5, 8, 'Turquoise', 'G-Series G20', 'Gas', 24, 69, 5062);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (6, 4, 'Khaki', 'Sable', 'Petrol', 36, 49, 4691);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (7, 15, 'Violet', 'Discovery Series II', 'Gas', 46, 22, 1962);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (8, 3, 'Fuscia', 'Savana 2500', 'Petrol', 70, 51, 3680);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (9, 12, 'Maroon', 'Savana 2500', 'Electric', 44, 77, 9096);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (10, 17, 'Teal', 'Exige', 'Petrol', 39, 79, 4605);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (11, 12, 'Puce', 'G-Series 2500', 'Gas', 51, 57, 7127);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (12, 12, 'Purple', 'Grand Marquis', 'Gas', 30, 100, 1750);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (13, 8, 'Goldenrod', 'XL-7', 'Electric', 30, 72, 4020);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (14, 3, 'Crimson', 'Azure T', 'Gas', 37, 53, 1677);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (15, 10, 'Maroon', 'Golf', 'Petrol', 61, 75, 5048);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (16, 3, 'Orange', 'IS', 'Diesel', 40, 67, 5507);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (17, 6, 'Fuscia', 'GTO', 'Diesel', 50, 49, 1622);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (18, 19, 'Maroon', 'LeMans', 'Petrol', 53, 97, 6425);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (19, 18, 'Goldenrod', 'H3', 'Diesel', 54, 41, 6572);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (20, 5, 'Pink', 'Tempo', 'Gas', 66, 91, 5364);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (21, 6, 'Khaki', 'Insight', 'Diesel', 42, 40, 3738);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (22, 18, 'Aquamarine', 'GTO', 'Petrol', 29, 57, 741);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (23, 8, 'Orange', 'Century', 'Diesel', 65, 73, 3148);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (24, 10, 'Violet', 'Frontier', 'Petrol', 51, 59, 2882);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (25, 13, 'Crimson', '530', 'Petrol', 67, 71, 6424);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (26, 20, 'Maroon', 'W201', 'Petrol', 46, 21, 2083);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (27, 19, 'Yellow', 'Crossfire', 'Petrol', 54, 78, 2652);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (28, 3, 'Goldenrod', 'LX', 'Diesel', 34, 25, 6100);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (29, 5, 'Puce', 'Explorer Sport Trac', 'Petrol', 34, 29, 7635);
insert into car (car_id, customer_id, color, model, fuel_type, mileage, powerc, car_number) values (30, 13, 'Khaki', 'Sienna', 'Electric', 22, 64, 5403);
